# Mandatory settings

blog_theme: dark # Or use dark
name: Edgar Nyandoro
paginate: 25
url: https://major2000.github.io
baseurl: ""

title: [Edgar Nyandoro]
description: [A short description of your site's purpose]

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Optional settings

about_enabled: true 
local_fonts: false
rss_enabled: false 
scrollappear_enabled: true 
tag_nav_enabled: false 
theme_toggle: false
social:
  dribbble:
  facebook:
  flickr: 
  github: major2000 
  linkedin: 
  twitter: Edgarmajor3
  email: edgarnyandoro23@gmail.com
  bitcoin: 
  ethereum:
  gitlab: 
  youtube: 
  twitch: 
  discord: 
  tumblr:
  bitbucket:
  docker:
  instagram:
  keybase:
  medium: 
  spotify: 
  stackoverflow:
  steam: 



assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    # permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
# plugins:
#   - jekyll-assets
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jemoji
paginate_path: /posts/page/:num/
# permalink: posts/:slug
